### ISSUE TITLE
working with jellyfin 10.8.13?

### ISSUE THREAD

**Issue by rantanlan** [tubearchivist/jellyfin#23]
can anyone confirm this is working with the latest version 10.8.13?
I'll just set this up and triple checked my setup but it won't find my "YouTube" Library in JF

Volume is mounted as in tubearchivist and name of the library is "YouTube" all under the same PUID and GUID

```
> docker exec -it tubearchivist-jf python main.py
[connection] verified jellyfin connection
[connection] verified tube archivist connection
Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    main()
  File "/app/main.py", line 13, in main
    library = Library()
              ^^^^^^^^^
  File "/app/src/series.py", line 19, in __init__
    self.yt_collection: str = self.get_yt_collection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/series.py", line 29, in get_yt_collection
    raise ValueError("youtube folder not found")
ValueError: youtube folder not found
```

**Comment by stonesbg** [comment]
I have this version.  Just double check that the actual folder that you have mounted into jellyfine is /youtube otherwise it won't find it.  I had initially called it /JF_YOUTUBE and hit the same issue.  If you need to you can add a print(folders) after line 24 and then you can see all the folder names returned https://github.com/tubearchivist/tubearchivist-jf/blob/master/app/src/series.py#L24.

Hope that helps

**Comment by rantanlan** [comment]
Ahh, thanks for the hint. I totally misunderstood this, I was under the impression the library in JF was supposed to be named youtube. Didn't get it was hardcoded to the folder... now it's working. Thanks again.
