### ISSUE TITLE
Media directory must be mounted at a directory named "youtube" inside the Jellyfin container

### ISSUE THREAD

**Issue by rockerbacon** [tubearchivist/jellyfin#27]
Detection of the YouTube "collection" (get_yt_collection in src/series.py) is based on the name of the folder within the Jellyfin docker container. Meaning if the mount for the Jellyfin container is defined as `/media/my_yt_library:/my_yt_library:ro`, for example, `get_yt_collection` will always fail. Mounting at any directory named "youtube" (case-insensitive) seems to work, eg `/library/YouTube`, `/my_media/internet/youtube`, etc.

I'm raising the issue because the README makes no mention of this requirement.

As a side question, would the maintainers welcome a PR to allow parameterizing the directory and library names through environment variables? I'm not a fan of the strict naming restrictions.

**Comment by lamusmaser** [comment]
This is a function of containerization. You are free to have whatever you like on the left-side, but the right-side should be easily determinable so that scripts don't have to be modified and we don't have to always reference another variable for base directory location (this also reduces potential conflicts within the container's filesystem). So, you should be able to have `/media/my_yt_library:/youtube:ro` and it will see it just fine because it is locally mounting that directory within the container at the expected location (`/youtube`).

If you are not utilizing the container, then you should be able to modify and point it to whichever directory you need to reference your media.

**Comment by rockerbacon** [comment]
@lamusmaser I believe you misunderstood the issue

**Comment by rockerbacon** [comment]
Just noticed the open PR, this is related to #20

**Comment by lamusmaser** [comment]
Ah, I have. You are talking about the actual JF container, not the JF-TA container. Thank you for the clarification.

**Comment by bbilly1** [comment]
you can now configure that, see readme.

But recommend to switch to the plugin: https://github.com/tubearchivist/tubearchivist-jf-plugin
